### ISSUE TITLE
hi Gabriele N. Tornetta

### ISSUE THREAD

**Issue by batmanm0b1E** [P403n1x87/blighty#10]
This is T.J Wolf from G+...  I was wondering if i can get those links again to what you sent me before. They took down G+ :( can't go back to get them. Also is conky group somewhere else let me know if it is. Thanks. Send me them through fb i sent you friend request

**Comment by P403n1x87** [comment]
Hi. You can find the code you're looking for in my gists: https://gist.github.com/P403n1x87
