### ISSUE TITLE
Change direction names

### ISSUE THREAD

**Issue by developomp** [P403n1x87/blighty#12]
change north, south, east, west to up, down, right, left respectively.
I don't see any reason why directions were named this way in the first place.

**Comment by P403n1x87** [comment]
Those names were chosen to align with similar properties of popular WMs. See, e.g.
- https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html
- https://valadoc.org/gdk-3.0/Gdk.Gravity.html

**Comment by developomp** [comment]
aah. It makes sense now. Thank you for a quick response!
