### ISSUE TITLE
NameError: name 'Fonts' is not defined

### ISSUE THREAD

**Issue by trappedinspacetime** [P403n1x87/blighty#14]
First of all, congrats on your project, I liked it.
I tried the examples. `clock.py` works but the rest of them gives errors.

          Traceback (most recent call last):
            File "cpu.py", line 9, in <module>
              from fonts import Fonts
          ImportError: cannot import name 'Fonts' from 'fonts' (/usr/local/lib/python3.8/dist-packages/fonts/__init__.py)
I installed fonts module `pip3 install fonts`.

**Comment by P403n1x87** [comment]
Ah! My apologies, it looks like I forgot to include the `fonts.py` module. This is simply exporting some font description constants under the namespace class `Fonts`. What you need is then a file named `fonts.py` with a content like this
~~~ python
import cairo

class Fonts(type):
    LAKSAMAN_NORMAL = "Laksaman", cairo.FontSlant.NORMAL, cairo.FontWeight.NORMAL
    LAKSAMAN_BOLD = "Laksaman", cairo.FontSlant.NORMAL, cairo.FontWeight.BOLD
    WEATHER_ICON_NORMAL = "Weather Icons", cairo.FontSlant.NORMAL, cairo.FontWeight.NORMAL
~~~

**Comment by trappedinspacetime** [comment]
@P403n1x87 Thank you for responding and your solution. I tried it and it works. 
All the best.
